Dev
deeramster/go_final_project pull request #1
Opened 2024-10-13 01:03 UTC by deeramster

2024-10-13 21:29 UTC, dirtymew requested changes
Привет Искандер

отличная работа:
 - хорошая документация
 - отличный github flow и docker compose
 - тесты проходят
 
но есть что поправить  - см комментарии

2024-10-13 21:29 UTC, dirtymew commented on .github/workflows/deploy.yml
> +        run: go test ./tests -v
очень круто получилось с github actions

2024-10-13 21:29 UTC, dirtymew commented on Dockerfile
> +RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o /scheduler ./main.go
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 - это лучше в ENV

2024-10-13 21:29 UTC, dirtymew commented on README.md
> +# Планировщик задач
круто что дописал документацию

2024-10-13 21:29 UTC, dirtymew commented on dateutil/dateutil.go
> +	startDate, err := time.Parse("20060102", date)
20060102 - стоило в константу вынести и везде использовать

2024-10-13 21:29 UTC, dirtymew commented on auth/auth.go
> +		pass := os.Getenv("TODO_PASSWORD")
тут не очень хорошее решение - делать запросы к os в хенлерах

syscall это очень дорого - стоит при старте приложение всю конфигурацию считать

2024-10-13 21:29 UTC, dirtymew commented on db/db.go
> +	_ "github.com/mattn/go-sqlite3"
импорты принято группировать на 2-3 группы

используй go imports и или настрой IDE

стоит везде поправить

2024-10-13 21:29 UTC, dirtymew commented on db/db.go
> +	dbFile := os.Getenv("TODO_DBFILE")
уже писал про вызовы к os выше - это плохо нужно исправить

2024-10-13 21:29 UTC, dirtymew commented on db/db.go
> +	db, err := sql.Open("sqlite3", dbFile)
тут тоже решение плохое - нужно переделать 

посмотри пример в задании про посылки там есть пример

проблема в том что кол-во подлючений к бд ограниченно - нужно создать одно подлючение и использовать его до конца работы приложения а по завершению не забыть закрыть...

2024-10-13 21:29 UTC, dirtymew commented on db/db.go
> +	rows, err := db.Query("SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 50")
лимит стоит вынести в константу

2024-10-13 21:29 UTC, dirtymew commented on db/db.go
> +func MarkTaskAsDone(taskID int, nextDate string) error {
Рекомендации по рефакторингу

- проверки лучше вынести в методы/функции и другие пакеты
- по структуре проекта https://github.com/golang-standards/project-layout
- по архитектуре - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10 и в задании про посылки можно подсмотреть как организованы service и storage

2024-10-13 21:29 UTC, dirtymew commented on db/db.go
> +              LIMIT 10`
лимит стоит один везде задать

2024-10-13 21:29 UTC, dirtymew commented on handlers/signin.go
> +		storedPassword := os.Getenv("TODO_PASSWORD")
тут таже проблема

2024-10-13 21:29 UTC, dirtymew commented on handlers/handlers.go
> +	w.Write([]byte(nextDate))
_ , _ = w.Write(resp)
тут стоит либо явно проигнорировать ошибку или ее логировать
хорошие линтеры на это ругаться будут и не зря

2024-10-13 21:29 UTC, dirtymew commented on handlers/handlers.go
> +		fmt.Printf("Comparing task date: %s with today's date: %s\n", taskDate.Format("20060102"), todayFormatted)
не стоит логировать все запросы - только ошибки

ну или использовать продвинуты логер с несколькими уровнями логирования - эта тема вне курсы - поэтому тут не буду требовать исправлять

2024-10-13 21:29 UTC, dirtymew commented on handlers/handlers.go
> +func HandleTask(w http.ResponseWriter, r *http.Request) {
очень прегруженный хендлер стоит разбить на несколько

2024-10-13 21:29 UTC, dirtymew commented on tests/settings.go
> +var Token = `123456`
это не jwt токен...

2024-10-15 01:15 UTC, deeramster commented on tests/settings.go
> +var Token = `123456`
Не одолел.

2024-10-15 18:54 UTC, dirtymew approved these changes
Привет Искандер

критичные моменты поправил - задание принимаю

Поздравляю и желаю удачи

2024-10-15 18:54 UTC, dirtymew commented on tests/settings.go
> +var Token = `123456`
ну не все сразу - работа и так отличная

2024-10-15 22:24 UTC, merged